### ISSUE TITLE
gra6-uni6 imagenes de sols en ENG (diagramas de línea dobles)

### ISSUE THREAD

**Issue by enriqueacosta** [enriqueacosta/IllustrativeMath-GrupoLEMA#120]
Reportado por @oterpater.

Hay que re-hacer las imágenes.

**Comment by oterpater** [comment]
Las imágenes que hasta ahora se deben traducir son:
6-6.3.D.PP_Image_1_answer
6-6.3.D2.PP.Image.Rev.0101.answer
6-6.3.D1.PP.Image.Rev.0404

**Comment by enriqueacosta** [comment]
@oterpater , en [77a4916](https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/commit/77a4916f48a917fc57c717b96b1008af32556c4f) reemplacé las imágenes por nuevas versiones de tikz. ¿Me ayudas porfa a revisar? (y cerrar este issue si ves todo bien)

**Comment by oterpater** [comment]
@enriqueacosta, revisado! Están perfectas!

**Comment by enriqueacosta** [comment]
Gracias @oterpater !
