### ISSUE TITLE
Act 1, lec 5, uni4gra3: ajustes tarjetas Todo sobre Bichos

### ISSUE THREAD

**Issue by veronicamariGNo** [enriqueacosta/IllustrativeMath-GrupoLEMA#135]
ISSUE: Act 1, tarjetas, situación A: “El grillo topo tiene unas patas especiales para cavar. Diez patas especiales pertenecen a 5 grillos topo. ¿Cuántas patas especiales tiene cada grillo topo?” lo quiero cambiar por “El grillo topo tiene varias patas. Algunas de ellas son especiales para cavar. En un grupo de 5 grillos topo se contaron diez patas especiales para cavar. ¿Cuántas patas especiales tiene cada grillo?”
ISSUE Act 1, tarjetas, situación C: “Catorce antenas pertenecen a un grupo de abejas.” lo quiero cambiar por: “En un grupo de abejas alguien contó catorce antenas.”
ISSUE Act 1, tarjetas, situación D: “Hay 12 alas.” cambiar por: “En un grupo de libélulas hay 12 alas.”
ISSUE Act 1, tarjetas, situación E: ”Treinta patas pertenecen a 5 hormigas.” cambiar por “Alguien contó treinta patas en un grupo de 5 hormigas.”
ISSUE Act 1, tarjetas, situación F: “En total, hay 50 manchas en 5 mariposas.” Quitar la coma.

**Comment by enriqueacosta** [comment]
@veronicamariGNo , así se ve bien?

![todoSobreBichos-tarjetas](https://github.com/user-attachments/assets/81a5508c-6609-4512-be91-64446ceff974)

**Comment by enriqueacosta** [comment]
Listo. Gracias @veronicamariGNo !
