### ISSUE TITLE
Arreglar warnings que está dando Pretext

### ISSUE THREAD

**Issue by enriqueacosta** [enriqueacosta/IllustrativeMath-GrupoLEMA#74]
Al correr `pretext build gra3-uni4-web-prof`, el build está dando unos WARNINGS que parecen indicar que hay partes del source que se están ignorando:
```bash
warning: * PTX:WARNING: Unstructured content within a list item is being ignored ("personas. Ejemplos de respuestas:")
*              located within: "act-gruposEnBusYAlmuerzo" (xml:id), "Grupos en el bus y grupos en el almuerzo" (title)
warning: * PTX:WARNING: Unstructured content within a list item is being ignored ("mesas. Ejemplos de respuestas:")
*              located within: "act-gruposEnBusYAlmuerzo" (xml:id), "Grupos en el bus y grupos en el almuerzo" (title)
warning: * PTX:WARNING: Unstructured content within a list item is being ignored ("Pregúntele a los que usaron una estrategia diferente:")
*              located within: "Síntesis de la actividad" (title)
warning: * PTX:WARNING: Unstructured content within a list item is being ignored (". (Ejemplo de respuestas:")
*              located within: "Síntesis de la actividad" (title)
warning: * PTX:WARNING: Unstructured content within a list item is being ignored ("personas. Ejemplos de respuestas:")
*              located within: "act-gruposEnBusYAlmuerzo" (xml:id), "Grupos en el bus y grupos en el almuerzo" (title)
warning: * PTX:WARNING: Unstructured content within a list item is being ignored ("mesas. Ejemplos de respuestas:")
*              located within: "act-gruposEnBusYAlmuerzo" (xml:id), "Grupos en el bus y grupos en el almuerzo" (title)
successful application of /home/vscode/.ptx/2.6.2/core/xsl/pretext-html.xsl
```

**Comment by enriqueacosta** [comment]
Parece que los WARNINGS son de "act-gruposEnBusYAlmuerzo" (xml:id), que veo que es de `source/gra3-uni4/gra3-uni4-secD-lec18-act2.ptx`, entonces @aguilulfo , FYI

**Comment by enriqueacosta** [comment]
Ya encontré el tipo de cosas que se están ignorando:
https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/blob/2dbcc7c941fe098475a398306f64d3bfdb3b7f2c/source/gra3-uni4/gra3-uni4-secD-lec18-act2.ptx#L21-L30

El problema ocurre en la línea 23, porque comienza un `<li>` complejo, sin un `<p>`.

El output se ve así:
<img width="614" alt="Screenshot 2024-09-22 at 4 12 16 PM" src="https://github.com/user-attachments/assets/f3464f33-e9ad-439e-8d43-7789ab748e55">

**Comment by enriqueacosta** [comment]
@aguilulfo , ¿le puedo encargar que los arregle? (hay varias instancias).

En el caso que menciono arriba, la forma de arreglarlo es simple. Hay que cambiar:
```xml
 <li><m>24</m> personas. Ejemplos de respuestas:
    <ul>
      ...
    </ul>
 </li>
```
por
```xml
 <li>
    <p><m>24</m> personas. Ejemplos de respuestas:</p>
    <ul>
      ...
    </ul>
 </li>
```

La razón es la siguiente: hay `<li>` de dos tipos:
*  Tipo 1: `<li>` que es solo una frase: `<li> f r a s e </li>` (sin `<p>`s)
* Tipo2: `<li>` con algo más de una frase: adentro del `<li>....</li>` debe ir HTML válido, y todo HTML válido debe ir adentro de algún tag. Entonces, puede ser:
  ```xml
    <li>
        <p> ....</p>
        <p>....</p>
        <ol>
            ....
        </ol>
        <p> ... </p>
    </li>
  ```

**Comment by enriqueacosta** [comment]
Instancias:
*  source/gra3-uni4/gra3-uni4-secD-lec18-act2.ptx 
    * sol (mencionado como ejemplo arriba)
    * síntesis https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/blob/2dbcc7c941fe098475a398306f64d3bfdb3b7f2c/source/gra3-uni4/gra3-uni4-secD-lec18-act2.ptx#L114-L120
    * ???
*  ??

**Comment by aguilulfo** [comment]
DONE, creería que todas!

**Comment by enriqueacosta** [comment]
@aguilulfo , genial. A futuro, puede poner el SHA del commit, para que se sepa en dónde lo arreglo y cómo fue el arreglo. 

En este caso, es [b76f99e](https://github.com/enriqueacosta/IllustrativeMath-GrupoLEMA/pull/75/commits/b76f99ea7a931f37bea9e9f16a0ab3c3eeb1c7d0) (si hace click en el link, va a ver el registro los cambios que hizo).

**Comment by enriqueacosta** [comment]
Ya quedó arreglado.
